# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: required

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy
    - sudo pip install Django
    - pip install djangorestframework
    - pip install psycopg2

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version
    - coverage3 --version

script:
    - make check

