FORMAT: 1A
HOST: http://www.yetanotherfootballdb.me

# YetAnotherFootballDB

YetAnotherFootballDB is a simple API that allows customers to view simple information about NFL divisions, teams, and players.  

# Group Divisions

## Divisions Collection [/api/divisions/?offset={offset}&limit={limit}]

+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Division to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Division to perform action with. Has example value.



### List first {limit} Divisions starting from {offset}. Queries are bounded by the number of divisions which is 8 [GET]
+ Response 200 (application/json)

        [
            {
                "division": "NFC West",
                "dimage": "static/images/nfc_west.jpg",
                "conference": "National Football Conference",
                "cimage": "static/images/nfc.jpg",
                "founded": "1967",
                "rchamp": "Seattle Seahawks",
                "mchamps": "San Francisco 49ers",
                "cnum": "19"
            },
            {
                "etc..."
            }
            
        ]

## Divisions [/api/divisions/{id}]
A single Division object with all its details

+ Parameters
    + id (required, string, `AFC East`) ... String `id` of the Division to perform action with. Has example value.

### Retrieve a Division [GET]
+ Response 200 (application/json)

             {
                "division": "NFC West",
                "dimage": "static/images/nfc_west.jpg",
                "conference": "National Football Conference",
                "cimage": "static/images/nfc.jpg",
                "founded": "1967",
                "rchamp": "Seattle Seahawks",
                "mchamps": "San Francisco 49ers",
                "cnum": "19"
            }


# Group Teams
## Teams Collection [/api/teams/?offset={offset}&limit={limit}]

+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Teams to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Teams to perform action with. Has example value.



### List first {limit} Teams starting from {offset}. Queries are bounded by the number of teams which is 32. [GET]
+ Response 200 (application/json)

        [
            {
                "team": "Dallas Cowboys",
                "division": "http://www.yetanotherfootballdb.me/api/divisions/7/",
                "timage": "static/images/cowyboys.png",
                "state": "TX",
                "city": "Arlington",
                "stadium": "AT&T Stadium",
                "simage": "https://upload.wikimedia.org/wikipedia/commons/2/29/Cowboys_stadium.JPG",
                "coach": "Jason Garrett",
                "established": "1960",
                "cchamps": "10",
                "schamps": "5"
            },
            {
                "etc..." : "more"
            }
        ]



## Teams [/api/teams/{id}]
A single Team object with all its details

+ Parameters
    + id (required, string, `New England Patriots`) ... String `id` of the Team to perform action with. Has example value.

### Retrieve a Team [GET]
+ Response 200 (application/json)


        {
                "team": "Dallas Cowboys",
                "division": "http://www.yetanotherfootballdb.me/api/divisions/7/",
                "timage": "static/images/cowyboys.png",
                "state": "TX",
                "city": "Arlington",
                "stadium": "AT&T Stadium",
                "simage": "https://upload.wikimedia.org/wikipedia/commons/2/29/Cowboys_stadium.JPG",
                "coach": "Jason Garrett",
                "established": "1960",
                "cchamps": "10",
                "schamps": "5"
        }
 

# Group Players
## Players Collection [/api/players/?offset={offset}&limit={limit}]
+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Players to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Players to perform action with. Has example value.



### List first {limit} Players starting from {offset}. Queries are bounded by the number of players which is 2880[GET]

+ Response 200 (application/json)

        [
            {
                "name": "Drew Brees",
                "team": "http://www.yetanotherfootballdb.me/api/teams/15/",
                "number": "9",
                "position": "QB",
                "height": "6-0",
                "weight": "209",
                "age": "36",
                "experience": "15",
                "college": "Purdue",
                "pimage": "http://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2580.png"
            },
            {
                etc...
            }
        ]

## Players [/api/players/{id}]
A single Player object with all its details

+ Parameters
    + id (required, number, `1`) ... Int `id` of the Player to perform action with. Has example value.

### Retrieve a Player [GET]
+ Response 200 (application/json)

        {
            "name": "Drew Brees",
            "team": "http://yetanotherfootballdb.me/api/teams/15/",
            "number": "9",
            "position": "QB",
            "height": "6-0",
            "weight": "209",
            "age": "36",
            "experience": "15",
            "college": "Purdue",
            "pimage": "http://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/2580.png"
        }
