FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# YetAnotherNFLDB

YetAnotherNFLDB is a simple API that allows customers to view simple information about NFL divisions, teams, and players.  

# Group Divisions

## Divisions Collection [/api/divisions/?offset={offset}&limit={limit}]

+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Division to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Division to perform action with. Has example value.



### List first {limit} Divisions starting from {offset}. Queries are bounded by the number of divisions which is 8 [GET]
+ Response 200 (application/json)

        [
            {
                "Conference": "American Football Conference",
                "League": "National Football League",
                "Sport": "American football",
                "Founded": "1960 (as the American Football League Eastern Division)",
                "No. of teams": ["Buffalo Bills", "Miami Dolphins", "New England Patriots", "New York Jets"],
                "Most recent champion(s)": "New England Patriots",
                "Most titles": " New England Patriots"
            },
            {
                "etc..."
            }
            
        ]

## Divisions [/api/divisions/{id}]
A single Division object with all its details

+ Parameters
    + id (required, string, `AFC East`) ... String `id` of the Division to perform action with. Has example value.

### Retrieve a Division [GET]
+ Response 200 (application/json)

             {
                "Conference": "American Football Conference",
                "League": "National Football League",
                "Sport": "American football",
                "Founded": "1960 (as the American Football League Eastern Division)",
                "No. of teams": ["Buffalo Bills", "Miami Dolphins", "New England Patriots", "New York Jets"],
                "Most recent champion(s)": "New England Patriots",
                "Most titles": " New England Patriots"
            }


# Group Teams
## Teams Collection [/api/teams/?offset={offset}&limit={limit}]

+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Teams to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Teams to perform action with. Has example value.



### List first {limit} Teams starting from {offset}. Queries are bounded by the number of teams which is 32. [GET]
+ Response 200 (application/json)

        [
            {
                "team": "New England Patriots",
                "division": "AFC East",
                "state": "Massachusetts",
                "city": "Foxborough",
                "stadium": "Gillette Stadium",
                "coach": "Bill Belichick",
                "established": "1960"
            },
            {
                "etc..." : "more"
            }
        ]



## Teams [/api/teams/{id}]
A single Team object with all its details

+ Parameters
    + id (required, string, `New England Patriots`) ... String `id` of the Team to perform action with. Has example value.

### Retrieve a Team [GET]
+ Response 200 (application/json)


        {
            "team": "New England Patriots",
            "division": "AFC East",
            "state": "Massachusetts",
            "city": "Foxborough",
            "stadium": "Gillette Stadium",
            "coach": "Bill Belichick",
            "established": "1960"
        }
 

# Group Players
## Players Collection [/api/players/?offset={offset}&limit={limit}]
+ Parameters
    + offset (required, number, `1`) ... number `offset` of the Players to perform action with. Has example value.
    + limit (required, number, `1`) ... number `limit` of the Players to perform action with. Has example value.



### List first {limit} Players starting from {offset}. Queries are bounded by the number of players which is 2880[GET]

+ Response 200 (application/json)

        [
            {
            "name": "Bailey, Dan",
            "team": "Dallas Cowboys",
            "number": "5",
            "position": "K",
            "height": "6'0",
            "weight": "195",
            "age": "27",
            "experience": "5",
            "college": "Oklahoma State",
            "player_image": "http://www.dallascowboys.com/sites/dallascowboys.com/files/styles/312x312/public/bai159977_15.png"
            },
            {
                etc...
            }
        ]

## Players [/api/players/{id}]
A single Player object with all its details

+ Parameters
    + id (required, number, `1`) ... Int `id` of the Player to perform action with. Has example value.

### Retrieve a Player [GET]
+ Response 200 (application/json)

        {
            "name": "Bailey, Dan",
            "team": "Dallas Cowboys",
            "number": "5",
            "position": "K",
            "height": "6'0",
            "weight": "195",
            "age": "27",
            "experience": "5",
            "college": "Oklahoma State",
            "player_image": "http://www.dallascowboys.com/sites/dallascowboys.com/files/styles/312x312/public/bai159977_15.png"
        }
